#stage 1
FROM node:alpine AS build
WORKDIR /app

COPY package.json /app/
RUN npm install
COPY . /app/
RUN npm run build --prod

FROM nginx:alpine AS final
COPY --from=build /app/dist/Ecommerce.Client /usr/share/nginx/html
