export const functionsName = {
  ReceiveNewMessage: 'ReceiveNewMessage',
  SendMessage: 'SendMessage',
  LoadMessages: 'LoadMessages',
  ReceiveMessageList: 'ReceiveMessageList',
  Notify: 'Notify',
  NotifyTyping: 'NotifyTyping',
  NotifyTypingToUser: 'NotifyTypingToUser',
  OnlineUsers: 'OnlineUsers',
  EditMessage: 'EditMessage',
  DeleteMessage: 'DeleteMessage',
  MessageEdited: 'MessageEdited',
  MessageDeleted: 'MessageDeleted',
  MarkMessageAsRead: 'MarkMessageAsRead',
  MarkAllMessagesAsRead: 'MarkAllMessagesAsRead',
  ReceiveMessageRead: 'ReceiveMessageRead',
  MarkMessagesAsRead: 'MarkMessagesAsRead',
  UpdateUserSidebar: 'UpdateUserSidebar',
  UpdateUserStatus: 'UpdateUserStatus',
  MarkMessagesAsReceived: 'MarkMessagesAsReceived'
};
